name: Collect V2
on:
  schedule:
    - cron: "0 22 * * *" # UTC+8 6am
  workflow_dispatch:

permissions:
  contents: write

env:
  TZ: Asia/Shanghai

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"

      - name: Install
        run: pip3 install -r requirements.txt

      - name: Collect
        run: python -u subscribe/collect.py --overwrite --easygoing

      - name: Publish all artifacts to data branch
        run: |
          test -f data/clash.yaml || { echo "clash.yaml not found"; exit 1; }
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan _collect
          git rm -rf -f --cached .
          git add data/
          git mv data/* .
          git commit -m "collect: $(date +'%Y-%m-%d %H:%M:%S')" --allow-empty
          git push -f origin _collect:data
